#!/usr/bin/env bash
# Vetted duplicate merges (same-name + same-domain, false positives removed).
# Review, then run:  bash run-merges.sh
set -e

node --env-file=.env.local merge-companies.mjs --keep 1059 --loser 1263 --write   # keep "Neste home"  drop "Neste SAF"
node --env-file=.env.local merge-companies.mjs --keep 7 --loser 1271 --write   # keep "Hy24"  drop "Hy24"
node --env-file=.env.local merge-companies.mjs --keep 9 --loser 1273 --write   # keep "VERDE HYDROGEN"  drop "Verde Hydrogen"
node --env-file=.env.local merge-companies.mjs --keep 14 --loser 1278 --write   # keep "Lhyfe"  drop "Lhyfe"
node --env-file=.env.local merge-companies.mjs --keep 8 --loser 1281 --write   # keep "Plug Power"  drop "Plug Power"
node --env-file=.env.local merge-companies.mjs --keep 1276 --loser 1285 --write   # keep "Linde"  drop "Linde"
node --env-file=.env.local merge-companies.mjs --keep 1277 --loser 1286 --write   # keep "First Hydrogen"  drop "First Hydrogen"
node --env-file=.env.local merge-companies.mjs --keep 2133 --loser 1290 --write   # keep "Hysata"  drop "Hysata"
node --env-file=.env.local merge-companies.mjs --keep 976 --loser 1293 --write   # keep "H2 Green Steel"  drop "H2 Green Steel"
node --env-file=.env.local merge-companies.mjs --keep 81 --loser 1321 --write   # keep "Oklo Inc"  drop "Oklo"
node --env-file=.env.local merge-companies.mjs --keep 84 --loser 1324 --write   # keep "Firefly Fusion"  drop "Firefly Fusion"
node --env-file=.env.local merge-companies.mjs --keep 91 --loser 1331 --write   # keep "Renaissance Fusion"  drop "Renaissance Fusion"
node --env-file=.env.local merge-companies.mjs --keep 88 --loser 1332 --write   # keep "Commonwealth Fusion Systems"  drop "Commonwealth Fusion Systems"
node --env-file=.env.local merge-companies.mjs --keep 1330 --loser 1357 --write   # keep "The Nuclear Company"  drop "The Nuclear Company"
node --env-file=.env.local merge-companies.mjs --keep 1337 --loser 1391 --write   # keep "X-Energy"  drop "X-energy"
node --env-file=.env.local merge-companies.mjs --keep 1044 --loser 1555 --write   # keep "ESS"  drop "ESS Tech, Inc."
node --env-file=.env.local merge-companies.mjs --keep 1042 --loser 1556 --write   # keep "Invinity Energy Systems"  drop "Energy Storage Beyond Lithium / Invinity Energy Systems"
node --env-file=.env.local merge-companies.mjs --keep 1652 --loser 1700 --write   # keep "Kitty Hawk"  drop "Kitty Hawk"
node --env-file=.env.local merge-companies.mjs --keep 1291 --loser 1807 --write   # keep "Ohmium"  drop "Ohmium"
node --env-file=.env.local merge-companies.mjs --keep 1295 --loser 1811 --write   # keep "Sunfire"  drop "Sunfire"
node --env-file=.env.local merge-companies.mjs --keep 1298 --loser 1814 --write   # keep "Hy2gen"  drop "HY2GEN"
node --env-file=.env.local merge-companies.mjs --keep 1338 --loser 1908 --write   # keep "TerraPower"  drop "TerraPower"
node --env-file=.env.local merge-companies.mjs --keep 2831 --loser 2036 --write   # keep "Star Catcher"  drop "Star Catcher"
node --env-file=.env.local merge-companies.mjs --keep 1637 --loser 2107 --write   # keep "Heart Aerospace"  drop "Heart Aerospace"
node --env-file=.env.local merge-companies.mjs --keep 1655 --loser 2111 --write   # keep "VoltAero"  drop "VoltAero"
node --env-file=.env.local merge-companies.mjs --keep 2712 --loser 2119 --write   # keep "DeCharge Network"  drop "DeCharge Network"
node --env-file=.env.local merge-companies.mjs --keep 2712 --loser 2724 --write   # keep "DeCharge Network"  drop "DeCharge Network"
node --env-file=.env.local merge-companies.mjs --keep 1292 --loser 2132 --write   # keep "Verdagy"  drop "Verdagy"
node --env-file=.env.local merge-companies.mjs --keep 1296 --loser 2141 --write   # keep "Enapter"  drop "Enapter"
node --env-file=.env.local merge-companies.mjs --keep 1335 --loser 2173 --write   # keep "NuScale Power"  drop "NuScale Power"
node --env-file=.env.local merge-companies.mjs --keep 2705 --loser 2352 --write   # keep "Wright Electric"  drop "Wright Electric"
node --env-file=.env.local merge-companies.mjs --keep 1639 --loser 2359 --write   # keep "Bye Aerospace"  drop "Bye Aerospace"
node --env-file=.env.local merge-companies.mjs --keep 1704 --loser 2367 --write   # keep "REGENT"  drop "Regent"
node --env-file=.env.local merge-companies.mjs --keep 1909 --loser 2433 --write   # keep "Monolith Corp"  drop "Monolith"
node --env-file=.env.local merge-companies.mjs --keep 1371 --loser 2521 --write   # keep "Curio"  drop "Curio"
node --env-file=.env.local merge-companies.mjs --keep 1355 --loser 2532 --write   # keep "Tokamak Energy"  drop "Tokamak Energy"
node --env-file=.env.local merge-companies.mjs --keep 1327 --loser 2535 --write   # keep "Focused Energy"  drop "Focused Energy"
node --env-file=.env.local merge-companies.mjs --keep 1326 --loser 2537 --write   # keep "Avalanche Energy"  drop "Avalanche Energy"
node --env-file=.env.local merge-companies.mjs --keep 1340 --loser 2543 --write   # keep "Flibe Energy"  drop "Flibe Energy"
node --env-file=.env.local merge-companies.mjs --keep 1319 --loser 2677 --write   # keep "Solarcookers"  drop "Solar Cookers International"
node --env-file=.env.local merge-companies.mjs --keep 1309 --loser 2684 --write   # keep "BioLite"  drop "BioLite"
node --env-file=.env.local merge-companies.mjs --keep 1635 --loser 2703 --write   # keep "Vertical Aerospace"  drop "Vertical Aerospace"
node --env-file=.env.local merge-companies.mjs --keep 1632 --loser 2704 --write   # keep "Volocopter"  drop "Volocopter"
node --env-file=.env.local merge-companies.mjs --keep 1643 --loser 2706 --write   # keep "ZeroAvia"  drop "ZeroAvia"
node --env-file=.env.local merge-companies.mjs --keep 1631 --loser 2707 --write   # keep "Wisk Aero"  drop "Wisk Aero"
node --env-file=.env.local merge-companies.mjs --keep 982 --loser 2709 --write   # keep "Electra"  drop "Electra"
node --env-file=.env.local merge-companies.mjs --keep 982 --loser 2723 --write   # keep "Electra"  drop "Electra"
node --env-file=.env.local merge-companies.mjs --keep 1423 --loser 2725 --write   # keep "Statiq"  drop "Statiq"
node --env-file=.env.local merge-companies.mjs --keep 1418 --loser 2729 --write   # keep "Zunder"  drop "Zunder"
node --env-file=.env.local merge-companies.mjs --keep 2161 --loser 2753 --write   # keep "Fortera"  drop "Fortera"
